export const actions = {
    GET_LIST: 'GET_LIST',
    SET_LIST: 'SET_LIST',
    ADD_TODO: "ADD_TODO",
    UPDATE_LIST: 'UPDATE_LIST',
    DELETE_ITEMS: 'DELETE_ITEMS',
    UPDATE_DELETED_LIST: 'UPDATE_DELETED_LIST',
    GET_MANAGE_LIST: 'GET_MANAGE_LIST',
    SET_MANAGE_LIST: 'SET_MANAGE_LIST',
    SHOW_TODOS_ITEMS: 'SHOW_TODOS_ITEMS',
    ADD_LIST: 'ADD_LIST',
    DELETE_LIST: 'DELETE_LIST'
}